'use client';
//import type { Metadata } from "next";
import "./globals.css";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { useState } from "react";
// import  "bootstrap/dist/css/bootstrap.min.css";
// import BootstrapClient from "../../components/BootstrapClient";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [queryClient] = useState(() =>  new QueryClient())
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
        { children }
        </QueryClientProvider>
        {/* <BootstrapClient /> */}
      </body>
    </html>
  );
}
