import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container mx-auto py-8">
          <div className="grid gap-4">
            <div className="bg-gray-200 p-4 rounded">
              First Row: One Column
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-gray-200 p-4 rounded">
                Second Row: First Column
              </div>
              <div className="bg-gray-200 p-4 rounded">
                Second Row: Second Column
              </div>     
            </div>
            <div className="grid grid-cols-3 gap-4">
              <div className="bg-gray-200 p-4 rounded">
                Third Row: First Column
              </div>
              <div className="bg-gray-200 p-4 rounded">
                Third Row: Second Column
              </div>    
              <div className="bg-gray-200 p-4 rounded">
                Third Row: Third Column
              </div>      
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
